Use full path to bconsole
The upgrade to stretch removed a compat symlink leading to tracebacks:

Traceback (most recent call last):
  File "/etc/bacula/scripts/volumes-delete-old", line 118, in <module>
    p = subprocess.Popen(['bconsole'], stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python3.5/subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1282, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'bconsole'